version: '3.1'

services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    env_file: ".env"

    volumes:
      - ./mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 5901:80
    environment:
      - PMA_HOST=db

  bot:
    build: .
    env_file: ".env"
